# Generated by Django 2.1.3 on 2018-11-23 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomUser', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinstitutional',
            old_name='notes',
            new_name='note',
        ),
        migrations.AlterField(
            model_name='user',
            name='email_domain',
            field=models.CharField(blank=True, choices=[('local', 'Local'), ('national', 'National'), ('international', 'International')], default='local', max_length=20, verbose_name='email domain reach'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='Informatics Staff'),
        ),
        migrations.AlterField(
            model_name='user',
            name='proxy_domain',
            field=models.CharField(blank=True, choices=[('local', 'Local'), ('national', 'National'), ('international', 'International')], default='local', max_length=20, verbose_name='proxy domain reach'),
        ),
        migrations.AlterField(
            model_name='user',
            name='proxy_quota_type',
            field=models.CharField(blank=True, choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='daily', max_length=20, verbose_name='proxy quota type'),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('blocked', 'Blocked'), ('inactive', 'Inactive')], default='active', max_length=20, verbose_name='status'),
        ),
    ]
