# Generated by Django 2.1.3 on 2018-11-30 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomUser', '0002_auto_20181123_0037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userenterprise',
            name='extension_number',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='extension number'),
        ),
        migrations.AlterField(
            model_name='userenterprise',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='phone number'),
        ),
    ]
