# Generated by Django 2.1.3 on 2018-11-30 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomUser', '0003_auto_20181130_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userenterprise',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='phone number'),
        ),
    ]
