# Generated by Django 2.1.3 on 2018-12-03 06:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('CustomUser', '0004_auto_20181130_1512'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passwordhistory',
            name='first',
        ),
        migrations.RemoveField(
            model_name='passwordhistory',
            name='forth',
        ),
        migrations.RemoveField(
            model_name='passwordhistory',
            name='second',
        ),
        migrations.RemoveField(
            model_name='passwordhistory',
            name='third',
        ),
        migrations.AddField(
            model_name='passwordhistory',
            name='date_password',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date password'),
        ),
        migrations.AddField(
            model_name='passwordhistory',
            name='password',
            field=models.CharField(default='', max_length=150, verbose_name='password'),
        ),
    ]
