# Generated by Django 2.1.3 on 2018-12-14 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EntStructure', '0004_auto_20181208_2337'),
        ('CustomUser', '0006_auto_20181206_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='userenterprise',
            name='area',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='EntStructure.Area'),
        ),
    ]
