# Generated by Django 2.1.3 on 2018-12-14 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0002_default_services'),
        ('CustomUser', '0008_userenterprise_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='services',
            field=models.ManyToManyField(blank=True, help_text='', related_name='services_set', related_query_name='services', to='Services.Service', verbose_name='services'),
        ),
    ]
