# Generated by Django 2.1.3 on 2018-12-14 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DistributionList', '0002_distributionlist_description'),
        ('CustomUser', '0009_user_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='distribution_list',
            field=models.ManyToManyField(blank=True, help_text='', related_name='distribution_list_set', related_query_name='distribution_list', to='DistributionList.DistributionList', verbose_name='distribution list'),
        ),
        migrations.AlterField(
            model_name='user',
            name='services',
            field=models.ManyToManyField(blank=True, help_text='', related_name='services_set', related_query_name='services', to='Services.Service', verbose_name='services'),
        ),
    ]
