# Generated by Django 2.1.3 on 2018-12-15 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomUser', '0010_auto_20181214_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='distribution_list',
            field=models.ManyToManyField(blank=True, help_text='', related_name='distribution_list_set', related_query_name='distribution_list', to='DistributionList.DistributionList', verbose_name='distribution list'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=30, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=150, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='services',
            field=models.ManyToManyField(blank=True, help_text='', related_name='services_set', related_query_name='services', to='Services.Service', verbose_name='services'),
        ),
    ]
