# Generated by Django 2.1.3 on 2018-12-15 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomUser', '0011_auto_20181215_0006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='proxy_domain',
        ),
        migrations.RemoveField(
            model_name='user',
            name='proxy_extra_quota_size',
        ),
        migrations.RemoveField(
            model_name='user',
            name='proxy_quota_size',
        ),
        migrations.RemoveField(
            model_name='user',
            name='proxy_quota_type',
        ),
        migrations.AddField(
            model_name='user',
            name='internet_domain',
            field=models.CharField(blank=True, choices=[('local', 'Local'), ('national', 'National'), ('international', 'International')], default='local', max_length=20, verbose_name='internet domain reach'),
        ),
        migrations.AddField(
            model_name='user',
            name='internet_extra_quota_size',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='internet extra quota size'),
        ),
        migrations.AddField(
            model_name='user',
            name='internet_quota_size',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='internet quota size'),
        ),
        migrations.AddField(
            model_name='user',
            name='internet_quota_type',
            field=models.CharField(blank=True, choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='daily', max_length=20, verbose_name='internet quota type'),
        ),
        migrations.AlterField(
            model_name='user',
            name='distribution_list',
            field=models.ManyToManyField(blank=True, help_text='', related_name='distribution_list_set', related_query_name='distribution_list', to='DistributionList.DistributionList', verbose_name='distribution list'),
        ),
        migrations.AlterField(
            model_name='user',
            name='services',
            field=models.ManyToManyField(blank=True, help_text='', related_name='services_set', related_query_name='services', to='Services.Service', verbose_name='services'),
        ),
    ]
