# Generated by Django 2.1.3 on 2019-08-19 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CustomUser', '0012_auto_20190114_0135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='distribution_list',
            field=models.ManyToManyField(blank=True, help_text='', limit_choices_to={'is_active': True, 'service_type': 'distribution'}, related_name='distribution_list_set', related_query_name='distribution_list', to='Services.Service', verbose_name='distribution list'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, unique=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='services',
            field=models.ManyToManyField(blank=True, help_text='', limit_choices_to={'is_active': True, 'service_type': 'security'}, related_name='services_set', related_query_name='services', to='Services.Service', verbose_name='services'),
        ),
        migrations.AlterField(
            model_name='user',
            name='session_key',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='session Key'),
        ),
        migrations.AlterField(
            model_name='userenterprise',
            name='area',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='EntStructure.Area', verbose_name='Area'),
        ),
        migrations.AlterField(
            model_name='userenterprise',
            name='department',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='EntStructure.Department', verbose_name='Department'),
        ),
    ]
