# Generated by Django 2.1.3 on 2018-12-15 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomUser', '0012_auto_20181215_0023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='distribution_list',
            field=models.ManyToManyField(blank=True, help_text='', related_name='distribution_list_set', related_query_name='distribution_list', to='DistributionList.DistributionList', verbose_name='distribution list'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email_buzon_size',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='email buzon size'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email_message_size',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='email messages size'),
        ),
        migrations.AlterField(
            model_name='user',
            name='internet_extra_quota_size',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='internet extra quota size'),
        ),
        migrations.AlterField(
            model_name='user',
            name='internet_quota_size',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='internet quota size'),
        ),
        migrations.AlterField(
            model_name='user',
            name='services',
            field=models.ManyToManyField(blank=True, help_text='', related_name='services_set', related_query_name='services', to='Services.Service', verbose_name='services'),
        ),
    ]
