# Generated by Django 2.1.3 on 2018-12-15 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomUser', '0013_auto_20181215_0114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='distribution_list',
            field=models.ManyToManyField(blank=True, help_text='', related_name='distribution_list_set', related_query_name='distribution_list', to='DistributionList.DistributionList', verbose_name='distribution list'),
        ),
        migrations.AlterField(
            model_name='user',
            name='ftp_size',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='ftp size'),
        ),
        migrations.AlterField(
            model_name='user',
            name='services',
            field=models.ManyToManyField(blank=True, help_text='', related_name='services_set', related_query_name='services', to='Services.Service', verbose_name='services'),
        ),
    ]
