# Generated by Django 2.1.3 on 2019-08-19 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EntStructure', '0006_auto_20190819_1651'),
        ('CustomUser', '0013_auto_20190819_1615'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userenterprise',
            name='area',
        ),
        migrations.RemoveField(
            model_name='userenterprise',
            name='department',
        ),
        migrations.AddField(
            model_name='user',
            name='area',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='EntStructure.Area', verbose_name='Area'),
        ),
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='EntStructure.Department', verbose_name='Department'),
        ),
        migrations.AlterField(
            model_name='user',
            name='distribution_list',
            field=models.ManyToManyField(blank=True, help_text='', limit_choices_to={'is_active': True, 'service_type': 'distribution'}, related_name='distribution_list_set', related_query_name='distribution_list', to='Services.Service', verbose_name='distribution list'),
        ),
        migrations.AlterField(
            model_name='user',
            name='services',
            field=models.ManyToManyField(blank=True, help_text='', limit_choices_to={'is_active': True, 'service_type': 'security'}, related_name='services_set', related_query_name='services', to='Services.Service', verbose_name='services'),
        ),
    ]
