# Generated by Django 2.1.3 on 2019-10-17 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomUser', '0016_auto_20190820_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_supervisor',
            field=models.BooleanField(default=False, help_text='Designates whether the user can supervise system data.', verbose_name='Supervisor Staff'),
        ),
        migrations.AlterField(
            model_name='user',
            name='distribution_list',
            field=models.ManyToManyField(blank=True, help_text='', limit_choices_to={'is_active': True, 'service_type': 'distribution'}, related_name='distribution_list_set', related_query_name='distribution_list', to='Services.Service', verbose_name='distribution list'),
        ),
        migrations.AlterField(
            model_name='user',
            name='services',
            field=models.ManyToManyField(blank=True, help_text='', limit_choices_to={'is_active': True, 'service_type': 'security'}, related_name='services_set', related_query_name='services', to='Services.Service', verbose_name='services'),
        ),
        migrations.AlterField(
            model_name='userenterprise',
            name='outside',
            field=models.BooleanField(default=False, help_text='Check this options if user is outside of the county.', verbose_name='Is Outside?'),
        ),
    ]
