# Generated by Django 2.1.3 on 2020-06-11 13:35

import Help.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Help',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_es', models.CharField(default=True, max_length=50, verbose_name='name (es)')),
                ('name_en', models.CharField(default=True, max_length=50, verbose_name='name (en)')),
                ('description_es', models.TextField(default='', verbose_name='description (es)')),
                ('description_en', models.TextField(default='', verbose_name='description (en)')),
                ('attachment_es', models.FileField(blank=True, upload_to=Help.models.help_es_directory_path, verbose_name='attachment (es)')),
                ('attachment_en', models.FileField(blank=True, upload_to=Help.models.help_en_directory_path, verbose_name='attachment (en)')),
            ],
            options={
                'verbose_name': 'help',
                'verbose_name_plural': 'helps',
                'db_table': 'help',
            },
        ),
    ]
