# Generated by Django 2.1.3 on 2020-06-11 11:48
from django.db import migrations

def add_default_help(apps, schema_editor):
    Help = apps.get_model('Help', 'Help')
    # User Manual
    Help.objects.create(
        name_en="User manual",
        name_es="Manual de usuario",
        description_en= "",
        description_es= "",
        attachment_en=None,
        attachment_es=None
    )

    # Administration Manual
    Help.objects.create(
        name_en="Administration manual",
        name_es="Manual de adminstración",
        description_en="",
        description_es="",
        attachment_en=None,
        attachment_es=None
    )

    # Supervisor Manual
    Help.objects.create(
        name_en="Supervisor manual",
        name_es="Manual de supervisores",
        description_en="",
        description_es="",
        attachment_en=None,
        attachment_es=None
    )

    # Change Password Manual
    Help.objects.create(
        name_en="Change password manual",
        name_es="Manual para cambiar contraseña",
        description_en="",
        description_es="",
        attachment_en=None,
        attachment_es=None
    )

class Migration(migrations.Migration):

    dependencies = [
        ('Help', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_default_help),
    ]
