# Generated by Django 2.1.3 on 2018-12-11 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DistributionList', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='distributionlist',
            name='description',
            field=models.TextField(blank=True, verbose_name='description'),
        ),
    ]
