# Generated by Django 2.1.3 on 2019-10-31 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailServer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('name', models.CharField(default='', max_length=100, unique=True, verbose_name='name')),
                ('email_server', models.CharField(default='', max_length=128, verbose_name='email server')),
                ('email_port', models.PositiveIntegerField(default=25, verbose_name='email port')),
                ('email_username', models.CharField(default='', max_length=100, verbose_name='username')),
                ('email_password', models.CharField(default='', max_length=100, verbose_name='password')),
                ('use_tls', models.BooleanField(default=False, verbose_name='Use tls?')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Modified Date')),
            ],
            options={
                'verbose_name_plural': 'email servers',
                'verbose_name': 'email server',
                'db_table': 'email_server',
            },
        ),
    ]
