# Generated by Django 2.1.3 on 2019-11-03 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailserver',
            name='auth_required',
            field=models.BooleanField(default=False, verbose_name='authentication required'),
        ),
        migrations.AlterField(
            model_name='emailserver',
            name='email_password',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='password'),
        ),
        migrations.AlterField(
            model_name='emailserver',
            name='email_port',
            field=models.PositiveIntegerField(default=25, verbose_name='server port'),
        ),
        migrations.AlterField(
            model_name='emailserver',
            name='email_server',
            field=models.CharField(default='', max_length=128, verbose_name='server name or IP'),
        ),
        migrations.AlterField(
            model_name='emailserver',
            name='email_username',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='username'),
        ),
        migrations.AlterField(
            model_name='emailserver',
            name='use_tls',
            field=models.BooleanField(default=False, verbose_name='use tls?'),
        ),
    ]
