# Generated by Django 2.1.3 on 2018-12-29 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('name', models.CharField(default='', max_length=100, unique=True, verbose_name='name')),
                ('service_type', models.CharField(choices=[('security', 'Service'), ('distribution', 'Email Distribution List')], default='security', max_length=20, verbose_name='Type of Service')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='email')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('slugname', models.SlugField(blank=True, verbose_name='slugname')),
            ],
            options={
                'verbose_name': 'service',
                'verbose_name_plural': 'services',
                'db_table': 'services',
            },
        ),
    ]
