# Generated by Django 2.1.3 on 2018-12-09 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50, unique=True, verbose_name='name')),
                ('slugname', models.SlugField(default='', verbose_name='slugname')),
                ('description', models.TextField(blank=True, verbose_name='description')),
            ],
            options={
                'verbose_name': 'enterprise service',
                'db_table': 'enterprise_services',
                'verbose_name_plural': 'enterprise services',
            },
        ),
    ]
