# Generated by Django 2.1.3 on 2019-01-03 16:44

from django.db import migrations

def add_default_services(apps, schema_editor):
    Service = apps.get_model('Services', 'Service')
    # Internet Service
    Service.objects.create(is_active=True, name='Internet', service_type='security', slugname='internet',
                           description="Built-in service. This service can't be edited or removed.")

    # Email Service
    Service.objects.create(is_active=True, name='Email', service_type='security', slugname='email',
                           description="Built-in service. This service can't be edited or removed.")

    # Chat Service
    Service.objects.create(is_active=True, name='Chat', service_type='security', slugname='chat',
                           description="Built-in service. This service can't be edited or removed.")

    # Ftp Service
    Service.objects.create(is_active=True, name='Ftp', service_type='security', slugname='ftp',
                           description="Built-in service. This service can't be edited or removed.")

class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_default_services),
    ]
