# Generated by Django 2.1.3 on 2018-12-10 06:30

from django.db import migrations

def add_default_services(apps,schema_editor):
    Service = apps.get_model("Services","Service")
    general_description = "Built-in service. This service can't be changed or deleted."
    Service.objects.create(
        name="internet", description=general_description,slugname="internet"
    )
    Service.objects.create(
        name="email", description=general_description, slugname="email"
    )
    Service.objects.create(
        name="ftp", description=general_description, slugname="ftp"
    )
    Service.objects.create(
        name="chat", description=general_description, slugname="chat"
    )

class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_default_services),
    ]
