# Generated by Django 2.1.3 on 2019-11-05 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CheckExternalDB', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='externaldb',
            options={'verbose_name': 'external database', 'verbose_name_plural': 'external databases'},
        ),
        migrations.AddField(
            model_name='externaldb',
            name='notify_informatics_staff',
            field=models.BooleanField(default=True, verbose_name='notify informatics staff?'),
        ),
        migrations.AddField(
            model_name='externaldb',
            name='notify_supervisors_staff',
            field=models.BooleanField(default=True, verbose_name='notify supervisor staff?'),
        ),
        migrations.AlterField(
            model_name='externaldb',
            name='db_host',
            field=models.CharField(default='', max_length=128, verbose_name='DB server'),
        ),
        migrations.AlterField(
            model_name='externaldb',
            name='db_name',
            field=models.CharField(default='', max_length=64, verbose_name='DB name'),
        ),
        migrations.AlterField(
            model_name='externaldb',
            name='db_password',
            field=models.CharField(default='', max_length=64, verbose_name='DB password'),
        ),
        migrations.AlterField(
            model_name='externaldb',
            name='db_port',
            field=models.IntegerField(default=3306, verbose_name='DB port'),
        ),
        migrations.AlterField(
            model_name='externaldb',
            name='db_query',
            field=models.CharField(default='', help_text='You can use %s in your SQL query and it will be replaced for user field value chosen.', max_length=1024, verbose_name='DB SQL query'),
        ),
        migrations.AlterField(
            model_name='externaldb',
            name='db_username',
            field=models.CharField(default='', max_length=64, verbose_name='DB username'),
        ),
        migrations.AlterField(
            model_name='externaldb',
            name='user_action',
            field=models.CharField(choices=[('delete', 'Delete'), ('disable', 'Disable')], default='delete', max_length=20, verbose_name='user action'),
        ),
        migrations.AlterField(
            model_name='externaldb',
            name='user_field',
            field=models.CharField(choices=[('id', 'ID'), ('password', 'password'), ('last_login', 'last login'), ('is_superuser', 'superuser status'), ('username', 'username'), ('is_active', 'active'), ('date_joined', 'date joined'), ('polymorphic_ctype', 'polymorphic ctype'), ('is_staff', 'Informatics Staff'), ('is_supervisor', 'Supervisor Staff'), ('status', 'status'), ('password_date', 'password date'), ('first_name', 'first name'), ('last_name', 'last name'), ('email', 'email address'), ('email_buzon_size', 'email buzon size'), ('email_message_size', 'email messages size'), ('email_domain', 'email domain reach'), ('internet_quota_type', 'internet quota type'), ('internet_quota_size', 'internet quota size'), ('internet_extra_quota_size', 'internet extra quota size'), ('internet_domain', 'internet domain reach'), ('ftp_folder', 'ftp folder'), ('ftp_size', 'ftp size'), ('ftp_md5_password', 'ftp md5 password'), ('session_key', 'session Key'), ('area', 'Area'), ('department', 'Department'), ('user_ptr', 'user ptr'), ('enterprise_number', 'enterprise number'), ('ci_number', 'ci number'), ('phone_number', 'phone number'), ('extension_number', 'extension number'), ('authorized_document', 'authorized document'), ('note', 'note'), ('outside', 'Is Outside?')], default='id', max_length=100, verbose_name='user field'),
        ),
    ]
