# Generated by Django 2.1.3 on 2018-12-13 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LdapServer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('name', models.CharField(default='', max_length=100, unique=True, verbose_name='name')),
                ('server_host', models.CharField(default='', max_length=50, unique=True, verbose_name='server host')),
                ('server_port', models.PositiveIntegerField(default=389, verbose_name='server port')),
                ('start_tls', models.BooleanField(default=False, verbose_name='start tls')),
                ('bind_dn', models.CharField(default='', max_length=100, verbose_name='bind DN')),
                ('bind_password', models.CharField(default='', max_length=50, verbose_name='bind password')),
                ('email_domain', models.CharField(default='', max_length=50, verbose_name='email domain map')),
                ('email_buzon_size', models.CharField(default='', max_length=50, verbose_name='email buzon size map')),
                ('email_message_size', models.CharField(default='', max_length=50, verbose_name='email message size map')),
                ('proxy_domain', models.CharField(default='', max_length=50, verbose_name='proxy domain map')),
                ('proxy_quota_type', models.CharField(default='', max_length=50, verbose_name='proxy quota type map')),
                ('proxy_quota_size', models.CharField(default='', max_length=50, verbose_name='proxy quota size map')),
                ('proxy_extra_quota_size', models.CharField(default='', max_length=50, verbose_name='proxy extra quota size map')),
            ],
            options={
                'verbose_name_plural': 'ldap servers',
                'db_table': 'ldap_server',
                'verbose_name': 'ldap server',
            },
        ),
    ]
