# Generated by Django 2.1.3 on 2018-12-24 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LdapServer', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ldapserver',
            options={'verbose_name': 'active directory server', 'verbose_name_plural': 'active directory servers'},
        ),
        migrations.RemoveField(
            model_name='ldapserver',
            name='bind_dn',
        ),
        migrations.RemoveField(
            model_name='ldapserver',
            name='bind_password',
        ),
        migrations.AddField(
            model_name='ldapserver',
            name='admin_password',
            field=models.CharField(default='', max_length=50, verbose_name='admin password'),
        ),
        migrations.AddField(
            model_name='ldapserver',
            name='admin_username',
            field=models.CharField(default='', max_length=100, verbose_name='admin username'),
        ),
    ]
