# Generated by Django 2.1.3 on 2018-12-24 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LdapServer', '0002_auto_20181224_0147'),
    ]

    operations = [
        migrations.AddField(
            model_name='ldapserver',
            name='domain',
            field=models.CharField(default='', max_length=100, verbose_name='domain'),
        ),
        migrations.AddField(
            model_name='ldapserver',
            name='search_base',
            field=models.CharField(default='', max_length=100, verbose_name='search base'),
        ),
    ]
