# Generated by Django 2.1.3 on 2018-12-24 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LdapServer', '0003_auto_20181224_0155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ldapserver',
            name='proxy_domain',
        ),
        migrations.RemoveField(
            model_name='ldapserver',
            name='proxy_extra_quota_size',
        ),
        migrations.RemoveField(
            model_name='ldapserver',
            name='proxy_quota_size',
        ),
        migrations.RemoveField(
            model_name='ldapserver',
            name='proxy_quota_type',
        ),
        migrations.AddField(
            model_name='ldapserver',
            name='internet_domain',
            field=models.CharField(default='employeeType', max_length=50, verbose_name='proxy domain map'),
        ),
        migrations.AddField(
            model_name='ldapserver',
            name='internet_extra_quota_size',
            field=models.CharField(default='homeDrive', max_length=50, verbose_name='proxy extra quota size map'),
        ),
        migrations.AddField(
            model_name='ldapserver',
            name='internet_quota_size',
            field=models.CharField(default='employeeNumber', max_length=50, verbose_name='proxy quota size map'),
        ),
        migrations.AddField(
            model_name='ldapserver',
            name='internet_quota_type',
            field=models.CharField(default='division', max_length=50, verbose_name='proxy quota type map'),
        ),
        migrations.AlterField(
            model_name='ldapserver',
            name='email_buzon_size',
            field=models.CharField(default='otherMailbox', max_length=50, verbose_name='email buzon size map'),
        ),
        migrations.AlterField(
            model_name='ldapserver',
            name='email_domain',
            field=models.CharField(default='physicalDeliveryOfficeName', max_length=50, verbose_name='email domain map'),
        ),
        migrations.AlterField(
            model_name='ldapserver',
            name='email_message_size',
            field=models.CharField(default='postalCode', max_length=50, verbose_name='email message size map'),
        ),
    ]
