# Generated by Django 2.1.3 on 2019-07-25 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LdapServer', '0006_auto_20181224_0213'),
    ]

    operations = [
        migrations.AddField(
            model_name='ldapserver',
            name='domain_name',
            field=models.CharField(default='', max_length=50, unique=True, verbose_name='domain name'),
        ),
    ]
