# Generated by Django 2.1.3 on 2018-12-09 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EntStructure', '0002_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='is active'),
        ),
        migrations.AddField(
            model_name='department',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='is active'),
        ),
    ]
