# Generated by Django 2.1.3 on 2018-12-09 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EntStructure', '0003_auto_20181208_2308'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='slugname',
            field=models.SlugField(default='', verbose_name='slugname'),
        ),
        migrations.AddField(
            model_name='department',
            name='slugname',
            field=models.SlugField(default='', verbose_name='slugname'),
        ),
    ]
