# Generated by Django 2.1.3 on 2019-01-11 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EntStructure', '0004_auto_20181208_2337'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='area',
            name='email',
        ),
        migrations.RemoveField(
            model_name='department',
            name='email',
        ),
    ]
